spring.application.name=product-service
spring.ai.openai.enabled=false
server.port=8082
spring.application.name=product-service

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=productdb

spring.autoconfigure.exclude=org.springframework.ai.autoconfigure.vectorstore.mongodb.MongoDBAtlasVectorStoreAutoConfiguration
